### ISSUE TITLE
Undo replace

### ISSUE THREAD

**Issue by mortenbirkelund** [yireo/magento2-replace-tools#1]
Awesome tool you have created. Really helpful for dealing with the bloatware that Adobe is adding to Magento2 these days. 

Lets say I want to replace everything you suggested using the replace-all, but I have one or 2 packages I want to exclude from this. Is there a way to still use your tool, and then just add these 2 packages in the composer.json in some way so that they are not replaced? It would make a neater composer.json than having to manually copy past all your replaces except the 2 packages I don't want to replace. 

I hope you have some experience with this and can help me out. Thanks in advance.

**Comment by jissereitsma** [comment]
No, unfortunately composer doesn't offer this as an option. It is either to use the `replace` rules from the package all-in-one, or copy them to your local `composer.json`.

**Comment by mortenbirkelund** [comment]
@jissereitsma Thank you for the quick answer.
