### ISSUE TITLE
Use require --dev

### ISSUE THREAD

**Issue by superdav42** [yireo/magento2-replace-tools#15]
Is there any reason this package should NOT be used in dev only?
I tried it in the "require-dev" section of composer.json and it works just the same. It's a dev to for managing composer.json so there should be no reason to have it installed in production. Since this package is concerned about only installing the minimum it seems appropriate that the Readme be updated to suggest it be installed only on dev with the command:
```
composer require yireo/magento2-replace-tools --dev
```

**Comment by jissereitsma** [comment]
> Is there any reason this package should NOT be used in dev only?

NO! :) Thanks for the PR
