### ISSUE TITLE
Replace vs disable

### ISSUE THREAD

**Issue by refueledinc** [yireo/magento2-replace-tools#4]
Thanks for creating and maintaining this, very useful!

I currently disable unused modules by simply disabling them in the `config.php`.

I was just wondering if there is any meaningful day-to-day site loading performance improvements between using the replace method vs the disable method.

**Comment by jissereitsma** [comment]
Unfortunately, I'm not creating those benchmarks. The composer installation time is obviously different and less files are needed on the server, so faster deployment. Also possibly less bugs because the code is not there to cause a bug.

Perhaps you can come up with a benchmark?

**Comment by refueledinc** [comment]
No worries. I was just wondering if you had any prior knowledge between the two methods.
